In [1]:
#read a dataframe from google drive
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')

df = pd.read_csv('/content/gdrive/My Drive/Colab_Notebooks/Sample_data/iris.csv')
df.head()

Mounted at /content/gdrive

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          NaN  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           NaN          3.1           1.5          0.2     5.5
4           5.0          3.6           1.4          0.2  setosa

In [2]:
#All the informations at a glance
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   149 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [3]:
#Describe all the columns
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    149.000000   149.000000    150.000000   149.000000
mean       5.851678     3.055034      3.758667     1.205369
std        0.824507     0.434871      1.764420     0.761292
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [4]:
#count values for a specific column
df['sepal_length'].value_counts()

5.0    10
6.3     9
5.1     9
6.7     8
5.7     8
5.5     7
5.8     7
6.4     7
6.0     6
4.9     6
6.1     6
5.4     6
5.6     6
6.5     5
4.8     5
7.7     4
6.9     4
5.2     4
6.2     4
7.2     3
4.6     3
6.8     3
4.4     3
5.9     3
6.6     2
4.7     2
7.6     1
7.4     1
4.3     1
7.9     1
7.3     1
7.0     1
4.5     1
5.3     1
7.1     1
Name: sepal_length, dtype: int64

In [5]:
#find specific rows with a condition
print(df[df['sepal_length']>7.6])

     sepal_length  sepal_width  petal_length  petal_width    species
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
131           7.9          3.8           6.4          2.0  virginica
135           7.7          3.0           6.1          2.3  virginica

In [6]:
#Correlation in between full table
df.corr()

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.114626      0.870215     0.814558
sepal_width      -0.114626     1.000000     -0.426487    -0.356127
petal_length      0.870215    -0.426487      1.000000     0.962314
petal_width       0.814558    -0.356127      0.962314     1.000000

In [7]:
#Correlation between specific two columns.
print("Correlation is:",df['petal_length'].corr(df['petal_width']))

# cor2 = df['petal_width']
# corr = cor1.corr(cor2)
# print(corr)

Correlation is: 0.9623142989595621

**CSV**

In [8]:
#Create a file with string
from io import StringIO, BytesIO
data = ('col1, col2, col3\n'
        'x, y, 1\n'
        'a, b, 2\n'
        'c, d, 3')
type(data)

str

In [9]:
#print the file with string datas
pd.read_csv(StringIO(data))

  col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [10]:
df = pd.read_csv(StringIO(data), usecols=['col1']) #usecols used to print a specifice column
print(df)

  col1
0    x
1    a
2    c

In [11]:
#Save the file

#read the string file by StringIO
df = pd.read_csv(StringIO(data))

#copy the main file and save by to_csv
test = df.copy()
test.to_csv('/content/gdrive/My Drive/Colab_Notebooks/Sample_data/test.csv')

#read the new file 'test'
import pandas as pd
from google.colab import drive
drive.mount('/content/gdrive')
test = pd.read_csv('/content/gdrive/My Drive/Colab_Notebooks/Sample_data/test.csv')
test.head()

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

   Unnamed: 0 col1  col2   col3
0           0    x     y      1
1           1    a     b      2
2           2    c     d      3

In [12]:
#Delete the extra column in the copied file
del test['Unnamed: 0']
test.head()

  col1  col2   col3
0    x     y      1
1    a     b      2
2    c     d      3

In [13]:
#Specifying columns data type
data = ('a,b,c,d\n'
          '1,2,3,4\n'
          '5,6,7,8\n'
          '9,10,11,12')
print(data)

a,b,c,d
1,2,3,4
5,6,7,8
9,10,11,12

In [14]:
#with dtype, you can print the datas as you want
df = pd.read_csv(StringIO(data), dtype=object)
print(df)

df = pd.read_csv(StringIO(data), dtype=float)
print("\n",df)

   a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

      a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [15]:
#Find a value from a dataframe by index (row and column)
print("The number is:", df['c'][1] , "present in the row 1 and col a")

The number is: 7.0 present in the row 1 and col a

In [16]:
df = pd.read_csv(StringIO(data), dtype={'a':float, 'b':int, 'c': object})
print(df)

     a   b   c   d
0  1.0   2   3   4
1  5.0   6   7   8
2  9.0  10  11  12

In [17]:
df.dtypes

a    float64
b      int64
c     object
d      int64
dtype: object

In [18]:
df['a'][2]

9.0

**Specify Index column**

In [19]:
data = ('index,a,b,c\n'
        '4,apple,bat,5,7\n'
        '8,orange,cow,10')
print(data)

index,a,b,c
4,apple,bat,5,7
8,orange,cow,10

In [20]:
df = pd.read_csv(StringIO(data), index_col=0)
print(df)

    index    a   b    c
4   apple  bat   5  7.0
8  orange  cow  10  NaN

In [21]:
data = ('a,b,c\n'
        '4,apple,bat,\n'
        '8,orange,cow')
df = pd.read_csv(StringIO(data))
print(df)

        a    b   c
4   apple  bat NaN
8  orange  cow NaN

In [22]:
#Assigned values are not designed succesfully in the row. So use index_col = False.
df = pd.read_csv(StringIO(data),index_col=False)
print(df)

   a       b    c
0  4   apple  bat
1  8  orange  cow

**Combined usecols and index_col**

In [23]:
data = ('colors,fruits,animals\n'
        'Black,Apple,Dog,\n'
        'White,Banana,Cow')
df = pd.read_csv(StringIO(data))
print(df)

       colors fruits  animals
Black   Apple    Dog      NaN
White  Banana    Cow      NaN

In [24]:
df = pd.read_csv(StringIO(data), usecols=['colors', 'animals'], index_col=False)
print(df)

  colors animals
0  Black     Dog
1  White     Cow

**Quoting and Escape characters.** *VERY USEFUL IN NLP.*

In [25]:
data = 'a,b\n"hello, \\"Bob\\", nice to see you", How are you?'
print(data)

a,b
"hello, \"Bob\", nice to see you", How are you?

In [26]:
df = pd.read_csv(StringIO(data), escapechar='\\')
print(df)

                               a              b
0  hello, "Bob", nice to see you   How are you?

**URL to CSV**

In [27]:
df = pd.read_csv('https://download.bls.gov/pub/time.series/cu/cu.item', sep='\t')
df.head()

  item_code  ... sort_sequence
0       AA0  ...             2
1      AA0R  ...           399
2       SA0  ...             1
3      SA0E  ...           374
4     SA0L1  ...           358

[5 rows x 5 columns]